[GLOBAL]
pants_version = "2.20.1"
backend_packages = ["pants.backend.python"]

[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock" }

[export]
py_resolve_format = "symlinked_immutable_virtualenv"
resolve = ["python-default"]
